#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR:$APPDIR/bin:/opt/Google/gwt-2.8.0/gwt-user.jar:/opt/Google/gwt-2.8.0/gwt-dev.jar" com.google.gwt.i18n.tools.I18NSync -out $APPDIR info.esblurock.reaction.chemconnect.core.client.resources.DataIdentifiers  ;

